# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 16:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ppt_download',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
